version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      # - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    # command: /usr/src/app/node_modules/.bin/nodemon app.js


networks:
  app-network:
    driver: bridge